
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/M1778/.cargo/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_2.6.2.0_x64__8wekyb3d8bbwe/"
      - "/mnt/c/Program Files/Common Files/Oracle/Java/javapath/"
      - "/mnt/c/Program Files/Alacritty/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/ProgramData/chocolatey/bin/"
      - "/mnt/c/Program Files/nodejs/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/Program Files/Git/mingw64/bin/"
      - "/mnt/c/Program Files/Git/usr/bin/"
      - "/mnt/c/Program Files/PowerShell/7/"
      - "/mnt/c/Program Files/komorebi/bin/"
      - "/mnt/c/Program Files/starship/bin/"
      - "/mnt/c/Program Files/YASB/"
      - "/mnt/c/Users/m1778/AppData/Local/Android/Sdk/"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "/mnt/c/Program Files/PuTTY/"
      - "/mnt/c/Program Files/cursor/resources/app/bin/"
      - "/mnt/c/Program Files/CMake/bin/"
      - "/mnt/c/Program Files/LLVM/bin/"
      - "/mnt/c/Program Files (x86)/LLVM/bin/"
      - "/mnt/c/Program Files/Docker/Docker/resources/bin/"
      - "/mnt/c/Users/m1778/scoop/shims/"
      - "/mnt/c/Users/m1778/.cargo/bin/"
      - "/mnt/c/Users/m1778/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/c/Users/m1778/AppData/Roaming/npm/"
      - "/mnt/c/Users/m1778/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "/mnt/c/Users/m1778/.rokit/bin/"
      - "/mnt/c/Users/m1778/AppData/Local/Programs/Antigravity/bin/"
      - "/mnt/c/Users/m1778/.bun/bin/"
      - "/mnt/c/Users/m1778/.local/bin/"
      - "/mnt/c/Users/m1778/AppData/Local/Microsoft/WinGet/Links/"
      - "/usr/bin/site_perl/"
      - "/usr/bin/vendor_perl/"
      - "/usr/bin/core_perl/"
    searched_directories:
      - "/home/M1778/.cargo/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/sbin/uname"
    search_context:
      ENV{PATH}:
        - "/home/M1778/.cargo/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Program Files/WindowsApps/MicrosoftCorporationII.WindowsSubsystemForLinux_2.6.2.0_x64__8wekyb3d8bbwe"
        - "/mnt/c/Program Files/Common Files/Oracle/Java/javapath"
        - "/mnt/c/Program Files/Alacritty/"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/Program Files/nodejs/"
        - "/mnt/c/Program Files/Git/cmd/"
        - "/mnt/c/Program Files/Git/mingw64/bin"
        - "/mnt/c/Program Files/Git/usr/bin"
        - "/mnt/c/Program Files/PowerShell/7/"
        - "/mnt/c/Program Files/komorebi/bin/"
        - "/mnt/c/Program Files/starship/bin/"
        - "/mnt/c/Program Files/YASB/"
        - "/mnt/c/Users/m1778/AppData/Local/Android/Sdk"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
        - "/mnt/c/Program Files/PuTTY/"
        - "/mnt/c/Program Files/cursor/resources/app/bin"
        - "/mnt/c/Program Files/CMake/bin"
        - "/mnt/c/Program Files/LLVM/bin"
        - "/mnt/c/Program Files (x86)/LLVM/bin"
        - "/mnt/c/Program Files/Docker/Docker/resources/bin"
        - "/mnt/c/Users/m1778/scoop/shims"
        - "/mnt/c/Users/m1778/.cargo/bin"
        - "/mnt/c/Users/m1778/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/c/Users/m1778/AppData/Roaming/npm"
        - "/mnt/c/Users/m1778/AppData/Local/Programs/Microsoft VS Code/bin"
        - "/mnt/c/Users/m1778/.rokit/bin"
        - "/mnt/c/Users/m1778/AppData/Local/Programs/Antigravity/bin"
        - "/mnt/c/Users/m1778/.bun/bin"
        - "/mnt/c/Users/m1778/.bun/bin"
        - "/mnt/c/Users/m1778/.local/bin"
        - "/mnt/c/Users/m1778/AppData/Local/Microsoft/WinGet/Links"
        - "/usr/bin/site_perl"
        - "/usr/bin/vendor_perl"
        - "/usr/bin/core_perl"
...
